name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tembo_nida_sdk:
    path: "/Users/mac/Downloads/Programs/temboplus/tembo_nida_sdk/"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: packages/tembo_core/fonts/IBMPlexSans/Light.ttf
          weight: 300
        - asset: packages/tembo_core/fonts/IBMPlexSans/Regular.ttf
          weight: 400
        - asset: packages/tembo_core/fonts/IBMPlexSans/Medium.ttf
          weight: 500
        - asset: packages/tembo_core/fonts/IBMPlexSans/SemiBold.ttf
          weight: 600
        - asset: packages/tembo_core/fonts/IBMPlexSans/Bold.ttf
          weight: 700

